version: '3.9'
services:
  fastapi-hello-world:
    image: fastapi-hello-world
    container_name: fastapi-hello-world
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Madrid
    restart: unless-stopped
    ports:
      - 8000:8000
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"